sudo: required
dist: trusty
addons:
    chrome: stable
language: node_js
node_js:
    - '12'
install:
    - npm ci
script:
    - npm run lint-lib
    - npm run test-lib-ci
    - npm run build-lib
    # - cd ../..
    # - ls
    # - ng new testProject
    # - cd ./testProject
    # - npm install ../damienbod/angular-auth-oidc-client/dist/angular-auth-oidc-client
    # - npm test -- --watch=false --browsers=ChromeHeadless
before_script:
    - npm install -g @angular/cli
notifications:
    email: false
notifications:
  slack: damienandfabian:jBlE2pSSKe18mysZZh1vtPUM
